export const GET_CATEGORY_NAVDATA_SUCCESS = 'GET_CATEGORY_NAVDATA_SUCCESS'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_BRANDDETAILSUCCESS = 'GET_BRANDDETAILSUCCESS'
export const GET_BRANDGOODSSUCCESS = 'GET_BRANDGOODSSUCCESS'